# Generated by Django 4.0.2 on 2022-02-26 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='shipping',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
